### ISSUE TITLE
Action Button Issue

### ISSUE THREAD

**Issue by iamnavi91** [codersaiful/woo-product-table#102]
There is no option to open action button in self tab.
I used this table for woocommerce booking. I want to open action button buy now in self tab, but it was only open in another tab. There is no option to set this.

**Comment by codersaiful** [comment]
Not clear, what did u mean? Need more explanation.

**Comment by iamnavi91** [comment]
means when i click on buy now button in table it open in another window..i want to open in self window..previous version it works, now in new version there is no option to do that..
There is another issue..in 2.9.1 version when i edit the table it hangs forever..how can i resolve that.

**Comment by hannannexus** [comment]
we tested that it's working fine. maybe your ajax action does not work or disable. we update our plugin. however, you can follow this link https://wooproducttable.com/enable-disable-ajax-action/  to solve your issue.

**Comment by iamnavi91** [comment]
it's resolved in latest update. thanx
