### ISSUE TITLE
Footer Cart hide if zero broken

### ISSUE THREAD

**Issue by mlstolk** [codersaiful/woo-product-table#110]
The Footer Cart hiding when there are no products on the shopping cart is broken. The Footer Cart button remains hidden, even when there are products added.

The code that I traced it back to does not check the amount (anymore?).
```
if(footer_cart === 'hide_for_zerro'){
                            FooterCart.fadeOut('slow');
}
```

**Comment by codersaiful** [comment]
Already solved this issue. Looking forward to hearing your response.
thanks
