### ISSUE TITLE
:  Illegal string offset 'cf_accredited_by' in line 23

### ISSUE THREAD

**Issue by uglyeoin** [codersaiful/woo-product-table#114]
I have this error occuring on any page with Woo Product table on it.  Please could you help me to figure out what it is?

Warning: Illegal string offset 'cf_accredited_by' in /home/site/public_html/wp-content/plugins/woo-product-table/includes/functions.php on line 23

Fatal error: Uncaught Error: Cannot use string offset as an array in /home/site/public_html/wp-content/plugins/woo-product-table/includes/functions.php:23 Stack trace: #0 /home/site/public_html/wp-includes/class-wp-hook.php(303): wpt_column_setting_for_tax_cf('', 142, Array) #1 /home/site/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array) #2 /home/site/public_html/wp-content/plugins/woo-product-table/includes/shortcode.php(87): apply_filters('wpto_column_set...', '', 142, Array) #3 /home/site/public_html/wp-includes/shortcodes.php(356): wpt_shortcode_generator(Array, '', 'Product_Table') #4 [internal function]: do_shortcode_tag(Array) #5 /home/site/public_html/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(Produc...', 'do_shortcode_ta...', '[Product_Table ...') #6 /home/site/public_html/wp-content/themes/Divi/includes/builder/class-et-builder-element.php(2770): do_shortcode('[Product_Table ...') #7 /home/devro in /home/site/public_html/wp-content/plugins/woo-product-table/includes/functions.php on line 23

There has been a critical error on this website.

I also see this information emailed to me.

Error Details
=============
An error of type E_ERROR was caused in line 23 of the file /home/devrolegroupco/public_html/wp-content/plugins/woo-product-table/includes/functions.php. Error message: Uncaught Error: Cannot use string offset as an array in /home/devrolegroupco/public_html/wp-content/plugins/woo-product-table/includes/functions.php:23
Stack trace:
#0 /home/devrolegroupco/public_html/wp-includes/class-wp-hook.php(303): wpt_column_setting_for_tax_cf('', 142, Array)
#1 /home/devrolegroupco/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array)
#2 /home/devrolegroupco/public_html/wp-content/plugins/woo-product-table/includes/shortcode.php(87): apply_filters('wpto_column_set...', '', 142, Array)
#3 /home/devrolegroupco/public_html/wp-includes/shortcodes.php(356): wpt_shortcode_generator(Array, '', 'Product_Table')
#4 [internal function]: do_shortcode_tag(Array)
#5 /home/devrolegroupco/public_html/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(Produc...', 'do_shortcode_ta...', '[Product_Table ...')
#6 /home/devrolegroupco/public_html/wp-content/themes/Divi/includes/builder/class-et-builder-element.php(2770): do_shortcode('[Product_Table ...')
#7 /home/devro

Is it possible product table clashes with DIVI?

**Comment by codersaiful** [comment]
Can you explain the situation? when this issue is coming. 
Looking forward to hearing your response.

**Comment by uglyeoin** [comment]
It comes on this page after I do an upgrade.  https://rolegroup.co.uk/upcoming-courses/

**Comment by codersaiful** [comment]
I have checked your site. you are using old version of our plugin. Please try with latest wordpress, latest woocommerce and latest wpt.
and let me know.
You also can contact with our support https://codeastrology.com/support
Our support agent will help you personally.
Thanks

**Comment by uglyeoin** [comment]
I have now updated all plugins except your plugin.  As soon as I do it breaks the site so I can't update it.

**Comment by uglyeoin** [comment]
I have raised a support ticket and will continue there.  Many thanks.

**Comment by codersaiful** [comment]
Ok, I an going to close this ticket.
