### ISSUE TITLE
Variation Table position in single product page

### ISSUE THREAD

**Issue by debugP** [codersaiful/woo-product-table#123]
Hello, 
I see in the Option page that there is the possibility of using  woo-product-table plugin to replace the default variation dropdown select options. We are at the moment using another plugin for that, and woo-product-table to display an Excel like product list.
Would be great if we could eliminate the other plugin and you only yours. But is I enable 
"Select a table and enable above the button to show a variation table on every variable product page which will replace the default variation dropdown select options." the variation table is positioned at the bottom of the page, while with the other plugin it is positioned at the top and there, with our theme (Enfold), it has a much better look. Also, it better for the client to know as soon as the page load how much does this product costs.
There is a snippet of code to move it to the top of the page?

Please see screenshots

Thank you 
Mauro
[Il Giglio di Firenze - The noblest perfume for the noblest city of Italy.pdf](https://github.com/codersaiful/woo-product-table/files/7260954/Il.Giglio.di.Firenze.-.The.noblest.perfume.for.the.noblest.city.of.Italy.pdf)
![Opera Snapshot_2021-09-30_180238_staging-naturalnicheperfume kinsta cloud](https://user-images.githubusercontent.com/22958868/135491224-52fa23d2-91a6-4eee-8605-99627461ee7f.png)

**Comment by codersaiful** [comment]
i need to ask about it my dev team but now our office is closed Its(GMT +6 Bangladesh) so i will tell you tomorrow morning

**Comment by fazlebarisn** [comment]
Yes, it's possible. 
Let me explain, woocommerce_single_product_summary hook display the table. Now you have to choose where you want to display the table. We choose the location by using 'woocommerce_after_single_product' hook.
So you can use woocommerce default hook or your theme's action hook to choose the location. 

Please see the reference here - https://gist.github.com/codeastrology-dev/93a729a4d770eb28da3c3a8d073433d4

**Comment by codersaiful** [comment]
We already ADDED more feature for this.
