### ISSUE TITLE
Product Add Ons not a column option in Product Table

### ISSUE THREAD

**Issue by Pcouso** [codersaiful/woo-product-table#128]
Hi,
I've been using Product Tables for Woocommerce for a little while and find it great for laying out a menu for a cafe website, however I'm trying to use a 'Product Addon' but Addons aren't an option to add as a column to my layout. I can add product variations but not Addons, it's had me stumped for a while so I'm hoping someone can help!

**Comment by codersaiful** [comment]
https://wooproducttable.com/enable-third-party-addons-support/

**Comment by Pcouso** [comment]
Thanks that worked but it's now made a complete mess of the table and brought in Subtotal, Add-ons total and Total fields, and the price is now no longer automatically updating when a different variation is selected?

**Comment by codersaiful** [comment]
ok we will check it and let you know

**Comment by codersaiful** [comment]
Support provided over ticker of  https://codeastrology.com/support 
Thanks for contacting with us.
