### ISSUE TITLE
Variation Table option not showing in Configure

### ISSUE THREAD

**Issue by jbrookechao** [codersaiful/woo-product-table#138]
### Discussed in https://github.com/codersaiful/woo-product-table/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **jbrookechao** October 28, 2021</sup>
I was looking up how to show product variations in a separate row, and found this in the documentation:
https://wooproducttable.com/show-product-variation-inside-table-on-a-single-variable-product-page/

I have the newest version of Woo Product Table Pro, but when I go to configuration, I don't see that line at all.</div>

**Comment by codersaiful** [comment]
please follow this screenshot, i hope you will find this option now

**Comment by jbrookechao** [comment]
There is no screenshot on your post.  I have followed the screenshots in your documentation (link in my post), and that option just does not appear in the current version of your plugin, which is 7.07, and what I am using on my site.

**Comment by fazlebarisn** [comment]
Our latest pro version is 8.0.0, Please download the latest version from codecanyon. You will get that option. 
Thanks

**Comment by jbrookechao** [comment]
I JUST purchased this in the last month or so.  Also, it doesn't show any updates in WordPress.  With a paid plugin shouldn't it alert you when it needs to be updated?

**Comment by fazlebarisn** [comment]
Please follow this documentation to get an auto update from codecanyon - https://wooproducttable.com/get-automatic-updates-from-codecanyon/

**Comment by jbrookechao** [comment]
I did follow that, but I purchased the plugin on your site, not on Envato, so needless to say, the plugin is not there.

**Comment by jbrookechao** [comment]
Maybe don't let people buy plugins on your site, if they are going to be required to have it in their envato account in order to get updates.  MOST plugins I have, on multiple sites, don't require these hoops to get timely updates.

**Comment by codersaiful** [comment]
We sell our plugin only Envato, Nowhere else. We only display our plugin on our site. If you click Buy button it will redirect to codecanyon page (Envato Market)

**Comment by codersaiful** [comment]
Variation Table select option in Configure page.
see Screenshot:
![image](https://user-images.githubusercontent.com/6463919/197448602-bba04bdf-f0d8-4934-8bd2-7a947336ce92.png)
For your kind information, For this feature, need pro version actually.
