### ISSUE TITLE
Testing Site vs Live Site + Additional Data appearing on Print Preview

### ISSUE THREAD

**Issue by epsoftwa** [codersaiful/woo-product-table#173]
Hello and thank you for a great product/plugin. (v 5.7.6)

The first issue we have is that we installed the Pro version on our testing site and when it came time to migrate to the Live site, we were unable to upload the plugin as we got an error during installation and we could only use the Free version.

The second issue is a Print/Print Preview issue. We have a table configured that displays on-screen perfectly, but when we go to print the page, all columns are displayed correctly, but an additional copy of the data for each row is displayed in the first cell of each row...!

What are we doing wrong???

01 - Front End Display - [https://epsoftwa.com.au/wp-content/uploads/Correct-display-on-front-end.jpg](url)

02 - Print Preview - [https://epsoftwa.com.au/wp-content/uploads/02-Incorrect-display-on-Print-Preview.jpg](url)

**Comment by codersaiful** [comment]
I can not see your url  image

**Comment by epsoftwa** [comment]
These are the direct links:

1 - https://epsoftwa.com.au/wp-content/uploads/Correct-display-on-front-end.jpg
2 - https://epsoftwa.com.au/wp-content/uploads/02-Incorrect-display-on-Print-Preview.jpg

**Comment by epsoftwa** [comment]
Or try these links:

1 - https://epsoftwa.com.au/woo-prod-table/woo-prod-table-issue-01.jpg
[https://epsoftwa.com.au/woo-prod-table/woo-prod-table-issue-01.jpg](url)

2 - https://epsoftwa.com.au/woo-prod-table/woo-prod-table-issue-02.jpg
[https://epsoftwa.com.au/woo-prod-table/woo-prod-table-issue-02.jpg](url)

**Comment by codersaiful** [comment]
You are using our pro old version ( v 5.7.6 ) and our current pro version is 8.0.2. 
First, give us your product purchase code and your table page link

**Comment by codersaiful** [comment]
we will check it and let you know

**Comment by codersaiful** [comment]
also, give us your site admin access.

**Comment by epsoftwa** [comment]
Sorry..... I've been testing while submitting this issue.

It is no longer an issue. I manage to solve it myself.

Under the first column header (SKU), I needed to turn OFF "To show Label of Item before Inside Item. | Inside Item Label (Checkbox) Unticked.

**Comment by epsoftwa** [comment]
Thank you for the quick response though :)

**Comment by codersaiful** [comment]
you are welcome:)

**Comment by epsoftwa** [comment]
We still have the issue of the Staging Site and Live site (it will only allow activation on the Staging site). We are not migrating the Staging site to the Live site all at once. As product ranges are migrated to WooCommerce we can test them on the staging site, then export products and import them into the live site. So while are technically using Woo Product Table on two websites, it's really only a Test site and a Live site. Is there a way around this or do we need to purchase an additional licence???

**Comment by codersaiful** [comment]
No, You no need to  purchase an additional license again

**Comment by codersaiful** [comment]
You can use both site ( Staging Site and Live site )

**Comment by epsoftwa** [comment]
Fair enough.

**Comment by codersaiful** [comment]
thank you

**Comment by epsoftwa** [comment]
> 

Not sure what you meant by this? Can I use the same license on the Staging and Live site or do I need two licences???

**Comment by codersaiful** [comment]
no

**Comment by epsoftwa** [comment]
Thank you.

**Comment by codersaiful** [comment]
you are welcome
