### ISSUE TITLE
Compatibility with other plugins

### ISSUE THREAD

**Issue by johnnita** [codersaiful/woo-product-table#175]
I am using WISDM Customer Specific Prices in order to import list of custom prices for each user role.
When I first load the product table page the prices are correct (the custom prices are displayed) but when I filter a category or search for a product or click 'Load more' the Regular prices are displayed instead of custom prices.
Exact same thing happens with Wholesale for Woocommerce plugin, which I use to set the number of units are in a box so a customer can only buy in multiples of that qty (e.g. if a box of silicones has 24 units than a customer can only buy a minimum of 24 or a multiple of 24 - 24/48/72/etc.), when the page loads for the first time quantity next to add to cart button displays the minimum value as default but when I filter, search, load more, the default goes back to 1 :(
One way around this is to disable pagination and load more button, to display all 900 products and disable search but enable instant search. The problem with this is that I have to wait few minutes for the page to load :)

URL: https://development.arcbuildingproducts.ie/my-shopping-page/

Any help please?
Thanks,
John.

**Comment by codersaiful** [comment]
Hello  Jhonnita,

We need some time to check your issue so I will give you an update tomorrow.

**Comment by johnnita** [comment]
Thanks for your quick reply, if you need further clarification or admin credentials please let me know.
Cheers.

**Comment by codersaiful** [comment]
Ok, if needed then i Will know you

**Comment by fazlebarisn** [comment]
Enable third-party plugin support, it may solve your problem. https://wooproducttable.com/enable-third-party-addons-support/
If it's not solving your problem, please contact the support team. You may need customization.

**Comment by codersaiful** [comment]
https://wooproducttable.com/documentation/

**Comment by codersaiful** [comment]
Hope: this issue is solved. If u need any more help, Contact with contact@codeastrology.com or codersaful@gmail.com 
thanks.
I am closing this ticket.
