### ISSUE TITLE
"Link disable" option not saving on product

### ISSUE THREAD

**Issue by fyxed** [codersaiful/woo-product-table#178]
Hi Guys!
Look at this: https://vimeo.com/684736202/20a0389a8e

Any idea?
I'm using Versión 3.1.0 of the plugin
Versión 6.0.0 of WooCommerce

Thanks!

**Comment by codersaiful** [comment]
we have fixed it already and released an update on  wordpress.org

**Comment by codersaiful** [comment]
so update it and  try again

**Comment by codersaiful** [comment]
if still have a problem then let us know

**Comment by codersaiful** [comment]
Really sorry for that. Actually this already solved even uploaded to wp server. I just dont update version.
So in this situation: delete plugin and again install. Your problem will be solved.
For your kind information: no data will destroy.
Don’t worry.
N.B: within 2-3 days, I will update version also.
Thanks

**Comment by codersaiful** [comment]
https://wordpress.org/support/topic/radio-button-options-of-products-and-thumbnails-are-not-saved/

**Comment by codersaiful** [comment]
Plugin already updated to wp server

**Comment by fyxed** [comment]
Excellent!!
Thanks a lot!
