### ISSUE TITLE
Sorting for Numbers

### ISSUE THREAD

**Issue by gilconcepcion** [codersaiful/woo-product-table#203]
I have noticed when we sort numbers, instead of giving us correct order we are getting result based on the FIRST number 

so for instance, when we sort this 5 2 3 4 10 40 24 

the right result should  be 2 3 4 5 10 24 40

but instead we got 10 2 24 3 4 40 5

**Comment by gilconcepcion** [comment]
Up to this issue, i want to know if in any situation we can modify the sort issues by either doing some hooks? Thanks and I am hoping for your immediate response.

**Comment by fazlebarisn** [comment]
Can you please share your table page link?

**Comment by gilconcepcion** [comment]
https://krytar.com/products/couplers/directional-couplers/

**Comment by gilconcepcion** [comment]
@fazlebarisn any updates

**Comment by fazlebarisn** [comment]
Yes :) last day we released a new version on wordpress.org. You will get a new option under "Options/Basic/Conditions" Tab. The option name is 'DataTable'
Turn on that. https://prnt.sc/mAKI1WV8C9WK
Hopefully, it will solve your problem.

**Comment by gilconcepcion** [comment]
@fazlebarisn couple of things i observed when i turned that on, it does sort numerically correct but when i pressed the sort buttons the data disappears until i pressed page 1, 2 etc. 

is there a way we dont need to have a pagination, like literally displays all items in one page, and when we click sort it changes asc or desc. ?

**Comment by gilconcepcion** [comment]
@fazlebarisn here's what is going on 

https://www.loom.com/share/c65c12b6160a48f9b59c198972503614

**Comment by fazlebarisn** [comment]
We have a filter to pass datatable arr

Here is an example 

 function wpto_localize_datatable_callback( $DATATABLE ){
	$DATATABLE = [
		'paging' => false,
	];
	return $DATATABLE;
 }
add_action( 'wpto_localize_datatable' , 'wpto_localize_datatable_callback');

**Comment by gilconcepcion** [comment]
@fazlebarisn  @codersaiful  The code was simple disabling the pagination process, but what about the missing data when sorting is clicked

Thank you for your response

**Comment by fazlebarisn** [comment]
I am not getting that problem. Need to check your site. Please create a ticket at https://codeastrology.com/support/
Our support team will try to solve your problem.
Thanks

**Comment by gilconcepcion** [comment]
@fazlebarisn just to support your claim, i have disabled the almost all the plugins and this issue still persists

**Comment by codersaiful** [comment]
We have fixed that issue. for sorting: we have added special feature.
For any column, where available number, even number with text will also work.
But you have to add a class for that specific column. that class name is: `text_with_number `

![example](https://user-images.githubusercontent.com/6463919/179894783-604a801c-130b-4902-bc14-e8e01e6de035.png)

**Comment by gilconcepcion** [comment]
we are almost there but there's a little bit problem on sort 

https://prnt.sc/8PXW5C1QmxWa

it should arrange 

26.5, 18, 12.4, 8, 7, 4

**Comment by hannannexus** [comment]
Hello Gil Concepcion,

We have fixed your sorting issue and now it works fine. so pull this version ( https://prnt.sc/qgQpNsC6YvRm ).  After trying this latest version please let us know.

**Comment by codersaiful** [comment]
Sorting issue has been fixed. And now it's on Free version.
Thanks to all. I am closing this topic.
