### ISSUE TITLE
the quantity does not work after setting the filter or tag

### ISSUE THREAD

**Issue by m3-develop** [codersaiful/woo-product-table#213]
Hi, 
the quantity does not work after setting the filter or tag, if nothing is set on the filter, the quantity works correctly.
Can you help me with this problem?

**Comment by codersaiful** [comment]
Dear @m3-develop Need more explanation for your issue.
Can you provide screenshot also please.

Looking forward to hearing your response.
One more things: for any topic of Woo Product Table.
Check our Documentaton: https://wooproducttable.com/documentation/

**Comment by codersaiful** [comment]
Unable to understand, what did u mean. And we had waited many days. Now I am closing this topic.
thanks
