### ISSUE TITLE
Single variation option does not appers...

### ISSUE THREAD

**Issue by mehmettuz** [codersaiful/woo-product-table#216]
Hi, single variations option does not appers in add new column section.
<img width="1409" alt="Ekran Resmi 2022-07-19 23 53 16" src="https://user-images.githubusercontent.com/55285316/179846593-00b16b78-f577-4d39-a388-48ad54660912.png">

**Comment by codersaiful** [comment]
It's actually pro feature. 
Check Tutorial: https://wooproducttable.com/doc/table-options/show-variation-name-in-a-single-column/
Check Demo: https://demo.wooproducttable.com/show-variation-name-in-a-single-column/

**Comment by codersaiful** [comment]
You need latest version of pro and free version. still if not found this feature, you have to contact with our support using https://codeastrology.com/support and create a ticket with login details.

**Comment by codersaiful** [comment]
We have updated our plugin and now Variation colum will show automatically for Variable product.

**Comment by codersaiful** [comment]
For variable product, Our plugin will add Variation column automatically. Even if you want to set Variation column to any specific place. Add **Variation Names** column. there will show all variation one by one.
Thanks 
See Screenshot:
![image](https://user-images.githubusercontent.com/6463919/197448344-7730baa2-6fb5-45bf-8646-79073cdc5525.png)
