### ISSUE TITLE
For Newly Created Tables, YITH Quick View Buttons are Broken

### ISSUE THREAD

**Issue by superzat** [codersaiful/woo-product-table#237]
Tables made before this glitch work correctly and the Quick View Buttons behave as normal. 

However any new tables I create "Quick View" is misspelled "Qiuck View" by default and do not work. The buttons dont react when clicked on and dont open the YITH Quick View popup window.

**Comment by codersaiful** [comment]
When you are getting this error. Actually need to check your site. So please contact with our support https://codeastrology.com/support and create a ticket with site details.

**Comment by fazlebarisn** [comment]
Make sure you have installed the correct "Qiuck View". Beside YITH Quick View, we also have our own Quick View plugin.

plugin link- https://wordpress.org/plugins/ca-quick-view/
 
Can you please tell me which version you are using? also, if possible please share your site table page link.

**Comment by codersaiful** [comment]
@superzat Can you share screenshot of Error please. Please provide, So that we can solve that issue.
thanks

**Comment by codersaiful** [comment]
We have our own plugin for Quick View. Plugin name [Quick View by Code Astrology](https://wordpress.org/plugins/ca-quick-view/)
Raw Link: https://wordpress.org/plugins/ca-quick-view/
