### ISSUE TITLE
Hactoberfest - Contribute Issue: Spelling fix from Whole Plugin - If founded 

### ISSUE THREAD

**Issue by codersaiful** [codersaiful/woo-product-table#244]
This is actually for Hacktoberfest user. If any user found any issue for any world and spelling,  You are welcome to fix it. To work on this repository. Install [Woo Product Table - WordPress WooCommerce Plugin](https://wordpress.org/plugins/woo-product-table/ )  and check from dashboard -> product table [add table or edit table or configuration page etc]

## How to Contribute?
* Install plugin to your localhost WordPress site.
* Need WooCommerce Plugin. Actually it's a WooCommerce Addons Plugin.
* Go to Dashboard -> Product Table and check all menu of Product table
* Find out spelling mistake
* Pull https://github.com/codersaiful/woo-product-table latest or last branch
* [Optional]  Or you can create new brance with your preferred name.
* Fix spelling and Push your code.

## Command Example:
`git fetch origin`
`git checkout to_your_branch`

**Comment by fazlebarisn** [comment]
Added
