### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by signosis** [codersaiful/woo-product-table#254]
I was getting the following error after updating the plugin.

Getting Fatal error: Uncaught Error: Call to a member function get_id() on null in /www/wp-content/plugins/woo-product-table/inc/table/row.php:95

I read the post at [https://wordpress.org/support/topic/error-on-assing_property-on-the-table_body-2/]

I found that with latest update I was required to go back into all my older Product tables open them and resave them.  
What causes the Tables to be unpublished or corrupted?

Complete error when used on Post
Fatal error: Uncaught Error: Call to a member function get_id() on null in /www/wp-content/plugins/woo-product-table/inc/table/row.php:95 Stack trace: #0 /www/wp-content/plugins/woo-product-table/inc/shortcode.php(811): WOO_PRODUCT_TABLE\Inc\Table\Row->__construct(Object(WOO_PRODUCT_TABLE\Inc\Shortcode)) #1 /www/wp-content/plugins/woo-product-table/inc/shortcode.php(289): WOO_PRODUCT_TABLE\Inc\Shortcode->table_body() #2 /wordpress/wp-includes/shortcodes.php(356): WOO_PRODUCT_TABLE\Inc\Shortcode->shortcode(Array, '', 'Product_Table') #3 [internal function]: do_shortcode_tag(Array) #4 /wordpress/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(Produc...', 'do_shortcode_ta...', '

**Comment by signosis** [comment]
In a new post I did  just a shortcode and received this error
[[Product_Table id='279356' name='Subcategories']]



Fatal error: Uncaught Error: Call to a member function get_id() on null in /www/wp-content/plugins/woo-product-table/inc/table/row.php:95 Stack trace: #0 /www/wp-content/plugins/woo-product-table/inc/shortcode.php(811): WOO_PRODUCT_TABLE\Inc\Table\Row->__construct(Object(WOO_PRODUCT_TABLE\Inc\Shortcode)) #1 /www/wp-content/plugins/woo-product-table/inc/shortcode.php(289): WOO_PRODUCT_TABLE\Inc\Shortcode->table_body() #2 /wordpress/wp-includes/shortcodes.php(356): WOO_PRODUCT_TABLE\Inc\Shortcode->shortcode(Array, '', 'Product_Table') #3 [internal function]: do_shortcode_tag(Array) #4 /wordpress/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(Produc...', 'do_shortcode_ta...', '[Product_Table ...') #5 /wordpress/wp-includes/class-wp-hook.php(307): do_shortcode('[Product_Table ...') #6 /wordpress/wp-includes/plugin.php(191): WP_Hook->apply_filters('[Product_Table ...', Array) #7 /www/wp-content/plugins/wordpress-seo/src/builders/indexable-link-builder.php(103): apply_filters('the_content', '[Product_Table . in /www/wp-content/plugins/woo-product-table/inc/table/row.php on line 95

**Comment by signosis** [comment]
When I create a completely new table  I get this error

Error: on assing_property on the table_body!! [Get Tutorial for this issue from wpOrg.]

**Comment by fazlebarisn** [comment]
Can you please tell me which version were you using and in which version are you getting this error?

**Comment by signosis** [comment]
The newest version.

**Comment by signosis** [comment]
After we resaved the table, the issue we have is there are some settings
that were lost. For example the table was set to filter on products in a
given category, but now table shows all products.

Also we are getting a large padding space at the top of the table.

I will send screenshots later when I get back to work.

**Comment by codersaiful** [comment]
I already solved first issue. Now let me to fix your second issue.
Thanks

**Comment by codersaiful** [comment]
Finally solved All issue and plugin has been updated to latest version.
Please update your plugin. and let me know. Thanks

**Comment by codersaiful** [comment]
Dear @signosis Update also pro version please to get Best performance.
