### ISSUE TITLE
Help with Layout

### ISSUE THREAD

**Issue by kunjan-github** [codersaiful/woo-product-table#257]
I want to build this layout with the help of woocommerce with your plugin. 
![image](https://user-images.githubusercontent.com/76934179/200961521-4ffaa287-d767-4df4-a98d-b78308e57012.png)
[
![image](https://user-images.githubusercontent.com/76934179/200961543-e9cc340f-8b38-4172-a9fb-84da444021c8.png)
](URL)

Please help me.

**Comment by fazlebarisn** [comment]
Hello,
Please explain your requirement in English. ( Red text ) and if possible, share your page link as well
Thanks

**Comment by fazlebarisn** [comment]
Hello,

Sorry, I still do not understand. Is your product a variable product and you want to display every variation inside table and then they can add to cart?

Note: Your attachment image has another language. We only understand English and Bangla. 

If you want we can talk via google meet. let me know.

Thanks

**Comment by kunjan-github** [comment]
Tomorrow at what time u r available for meet ? let me know please

**Comment by codersaiful** [comment]
Actually Today I mean Friday and Saturday is our weekend so he will  available  on Sunday and talk with you

**Comment by kunjan-github** [comment]
Okay so fix the time on Sunday please.

**Comment by kunjan-github** [comment]
At what time today we can arrange a google meet? please revert back to me.

**Comment by fazlebarisn** [comment]
Today at 2:20 pm ( GMT +6 )
Meet link -  https://meet.google.com/whk-ydjx-nhh

You also can add me on Skype -  fazle.bari2

**Comment by kunjan-github** [comment]
I am in
