### ISSUE TITLE
New Buttons on frontend

### ISSUE THREAD

**Issue by ElPaso8** [codersaiful/woo-product-table#259]
Hi. after one of the latest updates, these buttons appeared...

Is this related to your plugin or to woo commerce?
<img width="1440" alt="Bildschirmfoto 2022-11-14 um 09 56 37" src="https://user-images.githubusercontent.com/46609249/201618034-e480e8e8-8b27-43cf-aefd-ffe2a9c24860.png">
web: projekt-nube.ch

**Comment by ElPaso8** [comment]
its there.
below the screen shot?
https://projekt-nube.ch

**Comment by ElPaso8** [comment]
I also See, that columns suddenly are sortable... that does not make any sense in my case.
It completely crashed my shop layout.
I am not able to find these settings in backend to disable again.
And it is not favorable to me, to have new feature auto-enabled. Its better to let admin choose to enable it.

**Comment by codersaiful** [comment]
Hello, Use following code using your theme's functions.php file or by any code snippet plugin.
To remove default soring.
```
add_filter('wpt_wrapper_class','wpt_custom_remove_default_sort');
function wpt_custom_remove_default_sort( $classes ){
    $key = array_search('wpt_column_sort',$classes);
    unset($classes[$key]);
    $key2 = array_search(' wpt_column_sort',$classes);
    unset($classes[$key2]);
    return $classes;
}
```

And about your **All check uncheck** button. Maybe u have set check column and any how u hide by css. So Edit table and unset check column. this button will hide automatically.

![image](https://user-images.githubusercontent.com/6463919/201634768-530edf63-7d01-4310-9484-3ec83dc7e4c7.png)

**Comment by codersaiful** [comment]
Tutorial: [How to remove column sorting in Woo Product Table](https://wooproducttable.com/doc/developer-docs/how-to-remove-column-sorting-in-woo-product-table/)
