### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by ElPaso8** [codersaiful/woo-product-table#260]
Hi,
First of all thanks for your feedback.
But why do you close this issue? I can not answer anymore and have to open a new one.

So let me say, Its a really bad practice to change existing configuration without any admin interaction.
I am almost sure that with your recent update my whole frontend was changed. 

I have checked all fields, and I have not active any checkboxes.
So I still can not remove these weird buttons. 
<img width="1440" alt="Bildschirmfoto 2022-11-14 um 13 28 07" src="https://user-images.githubusercontent.com/46609249/201660534-9b346069-8a4d-4903-a72d-0abf57173a94.png">

So the issue remains. 
All was good, and without my interaction the buttons showed up and the sorting was activated. how can this be?

**Comment by ElPaso8** [comment]
About the sorting issue. I don't want sorting at all. It was not possible a few days ago. Now people can click on the head table to sort. why did you change that default settings?

**Comment by ElPaso8** [comment]
Our business was a pilot project, which is going to continue in spring. I was really considering upgrading to pro, but with this chaos its an absolute no go for any web developer. sorry to say this.

**Comment by fazlebarisn** [comment]
Hello,
First of all, so sorry for closing your first issue. We tested many ways before the release update. Buy as you know, some issues are left behind. We would like to solve your issues. For that, we need to check in details. 
Please, Create a ticket at our support site - https://codeastrology.com/support/ticket/
Thanks

**Comment by fazlebarisn** [comment]
To solve your sorting issue - https://wooproducttable.com/doc/developer-docs/how-to-remove-column-sorting-in-woo-product-table/
Let me know is it working or not.

**Comment by fazlebarisn** [comment]
Hope, your problem has been solved.
