### ISSUE TITLE
checkboxes disappear when not selecting a template

### ISSUE THREAD

**Issue by JudithK87** [codersaiful/woo-product-table#263]
Sofar I love this product, just trying to make everything perfect. In order to make the table fit to my overall website design I selected "Design > Template None". 

This makes the buttons into my default website button/colors which is what I want. BUT the checkboxes are all hidden. Checking into the CSS, it seems like the opacity is set to zero (see screenshot of the inspection tab). I am now trying to modify it with extra css on the page but if it can be fixed would be better ;)

Thanks!
![Screenshot 2022-11-18 at 15 42 02](https://user-images.githubusercontent.com/79253900/202730682-4f5f43dc-e9f1-45eb-8755-a25f92724b83.png)

**Comment by fazlebarisn** [comment]
Please share your page link. 
Thanks

**Comment by JudithK87** [comment]
The page is https://newerapub.com/testpage/

**Comment by fazlebarisn** [comment]
I have fixed the checkbox issue. Please use https://github.com/codersaiful/woo-product-table/tree/3.3.2.1 branch 
Thanks

**Comment by JudithK87** [comment]
Thanks! Works perfect :)
