### ISSUE TITLE
Discount issue

### ISSUE THREAD

**Issue by adroma** [codersaiful/woo-product-table#267]
Hi, in my website I set a discount by role plugin, that works fine but in woo-product-table doesn't work, it shows only the regular price as you can see in the attachment. Thanks to all for the support.

**Comment by hannannexus** [comment]
please give us  a screenshot and tell us your role plugin name. After that, we will check it and let you know.

**Comment by hannannexus** [comment]
You can try to active our plugin third plugin support option. After enable this option your role plugin data will display in  our product table action column. 
You can follow this doc ( https://wooproducttable.com/docs/doc/table-options/enable-third-party-addons-support/ )  to active to active our plugin third plugin support option.
