### ISSUE TITLE
Allow decimal in min/max price query (change validation pattern) 

### ISSUE THREAD

**Issue by mlstolk** [codersaiful/woo-product-table#268]
I have a simple request:
Filtering a table's query by setting a minimum/maximum price works for integers only, but it would be very useful to allow floating point prices as well. E.g. minimum price of 0.01 (or 0,01 depending on the country's decimal separator).
For now, I just removed the _pattern_ attribute in the HTML and submitted the new value without problems. It would be convenient if this was just possible by default.

admin/tabs/query.php at lines 347 and 356 (remove the pattern & type, or change it to allow at least 2 decimal places), e.g.
`<input name="conditions[min_price]" data-name='min_price' value="<?php echo isset( $meta_conditions['min_price'] ) ?$meta_conditions['min_price'] : ''; ?>" id="wpt_product_min_price" class="wpt_fullwidth wpt_data_filed_atts ua_input">
`

**Comment by fazlebarisn** [comment]
Thank you for noticing that. Hopefully, next time you will contribute to our plugin.
Here is the updated code:

`<input name="conditions[max_price]" data-name='max_price' value="<?php echo isset( $meta_conditions['max_price'] ) ?$meta_conditions['max_price'] : ''; ?>" id="wpt_product_max_price" class="wpt_fullwidth wpt_data_filed_atts ua_input" type="number" step="0.001" pattern="[0-9]+([\.,][0-9]+)?">`

**Comment by fazlebarisn** [comment]
Codes are updated
