### ISSUE TITLE
withe space above of a woocomerce Product Table,

### ISSUE THREAD

**Issue by Alextender** [codersaiful/woo-product-table#269]
I need help with withe space above of a woocomerce Product Table, on source code shows multiple <p> tags, anybody know the reason or can you help me? 

atatch screenshots

![Captura de Pantalla 2022-12-12 a la(s) 19 48 13](https://user-images.githubusercontent.com/6921309/207199854-e0a27381-cba5-44f4-bfd3-b2717dda74c0.png)

![Captura de Pantalla 2022-12-12 a la(s) 19 49 57](https://user-images.githubusercontent.com/6921309/207199856-39dcc82f-3e18-4a89-a136-c32e543408b1.png)

![Captura de Pantalla 2022-12-12 a la(s) 19 48 03](https://user-images.githubusercontent.com/6921309/207199843-1cf5c42d-96bf-49e0-acdf-c8625ed0ff58.png)

https://nativexplor.com/web/tour/cancun-playa-tulum/

thanks in advance

**Comment by hannannexus** [comment]
Please create a ticket here ( https://codeastrology.com/support/ ).  After that, we will check your issue and give you an update.

**Comment by fazlebarisn** [comment]
Not contacting. Hopefully, the issue is solved.
