### ISSUE TITLE
If found this issue I get a date

### ISSUE THREAD

**Issue by robbertva** [codersaiful/woo-product-table#275]

**Comment by hannannexus** [comment]
please tell us more details about your issue.

**Comment by hannannexus** [comment]
Hello,
You are open a issue of our product table but did not tell us details about your issue. so please tell us more details.

**Comment by codersaiful** [comment]
Hello @robbertva Explain details, What did u want?
I have to close this issue, If you don't say anything.

Looking forward to hearing your response.
Thanks
Saiful

**Comment by codersaiful** [comment]
We are closing this issue. 
please reopen with details, If you have issue
