### ISSUE TITLE
Product title is not showing ! 

### ISSUE THREAD

**Issue by Jahid07** [codersaiful/woo-product-table#278]
Hi,

I am currently utilizing the free version of the Woo Product Table plugin and have noticed that the product title is not visible on the front end when using the provided shortcode.

Best Regards

**Comment by codeastrology-dev** [comment]
Please give us your product table page link and some screenshot.  After that, we will check it and let you know.

**Comment by Jahid07** [comment]
Hi 

Thank you for your quick response.  I have trouble shooting the issue & found that. The plugin conflict with the divi theme. If I uninstall the divi theme it works fine & shows me the product title. 

Here is the product table URL https://rankingbuilder.com/get-access-now/

Also here are the screenshot

<img width="942" alt="image" src="https://user-images.githubusercontent.com/13711340/214009411-62b670d5-a7b7-4566-892b-f896a0b18de5.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/13711340/214009532-e33bf28c-605c-4116-8871-c072a5056aee.png">

Best Regards 
Jahid

**Comment by Jahid07** [comment]
HI Thank you for your willingness to help me. Just let you know that. I have found the issue. The display was none for the title. There was custom CSS I just remove it from the Divi theme option & it just works fine.

**Comment by codersaiful** [comment]
You are welcome

**Comment by codersaiful** [comment]
And thank you to find out this issue and solve it
