### ISSUE TITLE
Product Table for WooCommerce

### ISSUE THREAD

**Issue by luxecreative** [codersaiful/woo-product-table#281]
There is a plugin conflict with the latest WooCommerce Payments Version 5.4.0. When trying to 'Capture the Charge' for the order, nothing happens when I click the button. I have performed a conflict test and found that 'Product Table for WooCommerce' is the plugin causing the issue. When I deactivated it, I was able to capture the charge for the order.

**Comment by codeastrology-dev** [comment]
Hello, 
We need to check your issue and we need to know more details. So please give us some screenshots and your product table page link. 

Also, you can give us your problem screenshots and site link at our support https://codeastrology.com/my-support/

After that, we will try to solve your issue.

**Comment by mdibrahimk48** [comment]
Hello,

I wanted to check in and see if you have managed to resolve the issue you were facing. If not, please don't hesitate to let me know. I'm here to assist you and provide any further support you may need.

Thank you for your time and cooperation.
