### ISSUE TITLE
Variable Product Table Sorting Issue

### ISSUE THREAD

**Issue by mivanhoffen** [codersaiful/woo-product-table#283]
Hello, I am having an issue where if the user sorts using any of the columns on my product table, they are unable to add the item to the cart. I can only add to cart from the default view. I have tried a fresh install of woo product table on a different website and the same issue persists. Any recommendations for fixing this?

**Comment by codersaiful** [comment]
Ok. I will check it and give you an update, very soon.

**Comment by codersaiful** [comment]
Hello

**Comment by codersaiful** [comment]
Hello,



I have checked this issue in localhost, and there are no problems such as. Will you please give your product table link? We need to check it.
