### ISSUE TITLE
The discount price is not shown

### ISSUE THREAD

**Issue by adroma** [codersaiful/woo-product-table#289]
Hi, I'm using a plugin that allows me to apply discounts on products based on the corresponding taxonomies. However, the discount is not shown on the table but the regular price. Shows the ---- with two equal prices. If I add the product to the cart, the regular and discounted prices are displayed correctly. This only happens with your plugin while the discount is displayed correctly on the loop page. Why? Thank you

**Comment by fazlebarisn** [comment]
Enable third-party plugin support.
The correct price should be display in action column.
Here is an helper doc link - https://wooproducttable.com/docs/doc/table-options/enable-third-party-plugin-support/

**Comment by adroma** [comment]
Hi, thanks for quick response, but, as you  can see in the attachment,
there isn't a way to enable it.


Il giorno ven 21 apr 2023 alle ore 04:45 Fazle Bari <
***@***.***> ha scritto:

**Comment by adroma** [comment]
Hi, as you can see, the price shows regular price but not sale price.

Il giorno ven 21 apr 2023 alle ore 08:04 Marcello Torraco <
***@***.***> ha scritto:

**Comment by adroma** [comment]
Hi, in the attachment you can see the error in a better way
thanks

Il giorno ven 21 apr 2023 alle ore 08:19 Marcello Torraco <
***@***.***> ha scritto:

**Comment by fazlebarisn** [comment]
please use the latest version and active the 'action' column
