### ISSUE TITLE
Menu after importing custom table style

### ISSUE THREAD

**Issue by AdamDJohnson** [codersaiful/woo-product-table#291]
Applies to the PRO version. After I've imported a style for a table of mine, it no longer lets me get back into the designer to edit the form again or tweak the demo the way I would like. The current workaround is make a whole new table and do not import anything

**Comment by fazlebarisn** [comment]
Could you go ahead and reload the table edit page and save it again? It may happen because of the version compatibility.
Please create a ticket at your support site. https://codeastrology.com/my-support/

**Comment by AdamDJohnson** [comment]
I tried, no success. I registered on codeastrology but it says I do not have a purchase in my history as I purchased on Envato

**Comment by mdibrahimk48** [comment]
Hello @**AdamDJohnson**,

Please create a ticket at this link: https://codeastrology.com/support/ 

This one is for Envato users.

Thanks!

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
