### ISSUE TITLE
Add to cart by quantity

### ISSUE THREAD

**Issue by libananii** [codersaiful/woo-product-table#292]
Hi,
Just tried your plugin, its aweseome.
Before I buy I miss a feature. see the video.
When I click on + it should add to cart automaticly in ajax.
Second this I disabled Pagination, the text above the table (Showing 1 - 3 out of 3) should be hidden.

Please reply so I can get the plugin and buy it.

Best Regards

**Comment by mdibrahimk48** [comment]
Hello @**libananii**,

Maybe you forget to send the video link. 
To automatically add to the cart you can use Quick Quantity (It's a Pro Feature)
On the other hand, you may use the AJAX enable/disable option and Pagination enable/disable option from - Option Tab ( https://prnt.sc/3sXyUI90a63u )

Please check and let me know.

Best Regards,
**Ibrahim**
Technical Support Engineer, **CodeAstrology**

**Comment by libananii** [comment]
Hi Ibrahim,

Sorry for missing attach the video.
Here it is.
________________________________
Från: Md. Ibrahim Khalil ***@***.***>
Skickat: den 20 juni 2023 03:01
Till: codersaiful/woo-product-table ***@***.***>
Kopia: libananii ***@***.***>; Author ***@***.***>
Ämne: Re: [codersaiful/woo-product-table] Add to cart by quantity (Issue #292)


Hello @libananii,

Maybe you forget to send the video link.
To automatically add to the cart you can use Quick Quantity (It's a Pro Feature)
On the other hand, you may use the AJAX enable/disable option and Pagination enable/disable option from - Option Tab ( https://prnt.sc/3sXyUI90a63u )

Please check and let me know.

Best Regards,
Ibrahim
Technical Support Engineer, CodeAstrology

**Comment by mdibrahimk48** [comment]
I am still not getting your video.

Please create a ticket at: https://codeastrology.com/my-support/

Thanks!

**Comment by codersaiful** [comment]
Hello,

We are waiting for your response.

Thanks!

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
