### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by AdamDJohnson** [codersaiful/woo-product-table#293]
I tried to create my own template to re-use on other tables, however when import is used, now the save button changes to a save with CNTRL+S button that is not clickable, and when the key combo is used, it attempts to save the webpage. This is the second issue I have found with the import export styles option

**Comment by mdibrahimk48** [comment]
Hello @AdamDJohnson,

Please send your product table page link, I have to check this issue from your site.
For getting long support from our technical support team please create a ticket at: https://codeastrology.com/my-support/

Thanks!

Best regards,
Ibrahim
WordPress Developer || Technical Support Engineer
CodeAstrology

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
