### ISSUE TITLE
[Product_Table id='2555' name='SHOP'] Error

### ISSUE THREAD

**Issue by misterwishstore** [codersaiful/woo-product-table#295]
i tried [Product_Table id='2555' name='SHOP'] but its not ok, showing error

**Comment by codersaiful** [comment]
Please send screenshot with error message

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
