### ISSUE TITLE
Search filter brings back incorrect results

### ISSUE THREAD

**Issue by maccerzzz** [codersaiful/woo-product-table#297]
Hi, I have installed the product table to this dev website - https://paulm518.sg-host.com/products/ , but the filters for tags and categories bring back incorrect results.

Any help appreciated.

Many thanks

**Comment by mdibrahimk48** [comment]
Hello @maccerzzz,

Actually, on any archive page - this table will show only this archive's products. We can change that by using shortcode atts. In this case, it's 'behavior'. Set behavior to normal.

So the shortcode will be like this **[Product_Table id='2941' name='yu' behavior='normal']**

So this table will display all the products from the store.

You can filter products inside the table's Query tab.

**You can also follow this helper doc:** https://wooproducttable.com/docs/doc/table-options/display-table-on-specific-archive-page-category-tag-attribute-page/

Please check and let me know. If you need more support you can create a ticket at: https://codeastrology.com/my-support/

Thanks!

Best regards,
**Ibrahim**
Technical Support Engineer, **CodeAstrology**

**Comment by maccerzzz** [comment]
Hi Ibrahim,

Thanks for getting back to me. 

I have added the shortcode  - [Product_Table id='2631' name='Products Category' behavior='normal'] as a separate table below the initial one on the page - https://paulm518.sg-host.com/products/

Still, when I search by category, it does not filter out the correct products related to the category chosen.

Best Regards,

Paul.

**Comment by mdibrahimk48** [comment]
Please create a ticket at: https://codeastrology.com/my-support/
I need more information for checking.

**Comment by mdibrahimk48** [comment]
I have solved this issue via a support ticket.
