### ISSUE TITLE
Not able to center the elements of the table

### ISSUE THREAD

**Issue by naresh130199** [codersaiful/woo-product-table#299]
Hi, I am not able to center the elements of the table , I have given it a lot of time, I have written center on the table configuration, but it was of no use, headings are centered, but the actual content was not.

**Comment by fazlebarisn** [comment]
Please share your table page link. You may need our pro version for that. 

Pro feature - https://prnt.sc/TfriCpXcbhk9

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
