### ISSUE TITLE
Table Header sort icon problem

### ISSUE THREAD

**Issue by MasterK999** [codersaiful/woo-product-table#302]
I am having a problem where the icons to sort columns in the table header are not appearing. It looks like Fontello is being used for these icons. Where are the fontello files being loaded so I can make sure they are loaded probperly?

**Comment by mdibrahimk48** [comment]
Hello @MasterK999,

If you want to remove our default column sorting (icon), then use our 'wpt_wrapper_class' filter hook. You may follow this documentation: https://wooproducttable.com/docs/doc/developer-docs/how-to-remove-column-sorting-in-woo-product-table/ 

Best regards,
Ibrahim
Technical Support Engineer, CodeAstrology
