### ISSUE TITLE
Woo Product Table Pro Update

### ISSUE THREAD

**Issue by jbrookechao** [codersaiful/woo-product-table#304]
I have this banner message saying that I need to update Woo Product Table Pro, but there doesn't appear to be a way to do that, and the "Get Updates" link in the dashboard leads me to a 404 error.  Anyone have any suggestions?

**Comment by fazlebarisn** [comment]
We have fixed the link in the latest version. 
You can download and install the latest version from Codecanyoun.

And you can follow its article to get an auto-update.  - https://codeastrology.com/get-automatic-updates-from-codecanyon/

**Comment by codersaiful** [comment]
[Cyber Security Month Offer] is running now on all WooCommerce Addon.

50% Discount on all products.
Check it out https://codeastrology.com/coupons/ and https://codeastrology.com/downloads/category/premium/

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
