### ISSUE TITLE
It doesn't show any fields in the edit table page in the woo product table plugin

### ISSUE THREAD

**Issue by Reyhaneh-Mehri** [codersaiful/woo-product-table#305]
Why is no field shown on the table edit page in the woo product table plugin on my site?
All interactions with other plugins and site templates, as well as the php version of the site, have also been checked
But this problem persists and cannot be solved

**Comment by fazlebarisn** [comment]
Please give me a screenshot of your problem.

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
