### ISSUE TITLE
Working Issue

### ISSUE THREAD

**Issue by AhmedDeveloper42** [codersaiful/woo-product-table#306]
if I'm clicking on the product table nothing's happening click is no working properly the spinner is not working and the product which i wanna add in the table it's not working please fi it as soon as possible i wanna work more on it. thanks

**Comment by codersaiful** [comment]
Can you share your table link please. So that we can check.  Otherwise contact with our support

**Comment by codersaiful** [comment]
https://codeastrology.com/my-support/

**Comment by mdibrahimk48** [comment]
The solution is provided by a support ticket. Thanks!
