### ISSUE TITLE
echo do_shortcode("[Product_Table id='104' name='test']");

### ISSUE THREAD

**Issue by Niava** [codersaiful/woo-product-table#307]
the php do_shortcode not working. it displayed the correct content for 1 s then get overwritten by other forms

**Comment by codersaiful** [comment]
Can you provide your table page link plz?
And u can check https://wooproducttable.com/documentation/

By the way, you should contact over ticket. 
https://codeastrology.com/my-support

**Comment by mdibrahimk48** [comment]
We are discussing this issue with our support ticket. So, we marked it as closed now.
