### ISSUE TITLE
Delete from cart not working

### ISSUE THREAD

**Issue by libananii** [codersaiful/woo-product-table#310]
When trying to delete anything from cart is just refreshing and nothing happens. If I refresh the page (F5) then the product I tried to delete is deleted. How do I fix this issue?

**Comment by mdibrahimk48** [comment]
Hi,

We have checked your site and found this Bug. We need more details about your site. Could you open a ticket at: https://codeastrology.com/my-support/

Our dedicated developer team will check and fix your issue.

Best regards,

**Comment by mdibrahimk48** [comment]
Hello, we are waiting for your response!

**Comment by mdibrahimk48** [comment]
Hello @libananii ,

As you are inactive we assume that your issue is fixed. If you need support please contact: https://codeastrology.com/my-support/

Best regards,
Ibrahim
