### ISSUE TITLE
Table doesn't show on page

### ISSUE THREAD

**Issue by Kirkaskivi** [codersaiful/woo-product-table#311]
Hi,

my product table worked fine for a while, but it stopped showing on my Shop page. I've tried deactivating the other plugins, re-installing the Product Table plugin. I've tried saving and re-publishing and creating new tables, but still no show. I have the latest Wordpress version and Astra theme.

**Comment by mdibrahimk48** [comment]
Hello,

We apologize for the inconvenience you're experiencing with our plugin. Is it stop showing the content in the Shop Page or just Stop Showing the Table? Could you share the URL? 

Maybe we have to check your site's environment.

**Please create a ticket at:** https://codeastrology.com/my-support/

Our technical team will check and give you a solution.

Best regards,
Team CodeAstrology

**Comment by Kirkaskivi** [comment]
Hi,

it stopped showing the table: https://hellstonerecords.com/shop/

Br,

Vesku

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mdibrahimk48** [comment]
To learn how to show product table on shop page you may follow this Tutorial: **[Link](https://wooproducttable.com/docs/doc/table-options/product-table-woocommerce-archive-category-tag-attribute-page/)**

**Comment by mdibrahimk48** [comment]
Hello,

We are waiting for your response!

**Comment by Kirkaskivi** [comment]
Hi,

I re-opened the ticket and don't see replies there after it.

Br,

V[Näyttökuva 2023-12-29 201728.png]esku

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by codersaiful** [comment]
Ticket number please...

**Comment by codersaiful** [comment]
336?

**Comment by mdibrahimk48** [comment]
We have provided your answer in the ticket. So we closed this issue from here.
