### ISSUE TITLE
Complex Plugin With no Help information available anywhere. 

### ISSUE THREAD

**Issue by bluewatersmarine** [codersaiful/woo-product-table#312]
Hi,

Your plugin is so complex you need a genius to figure it out. I was able to do with in what I want one time but now I cannot. Your documentation relates to an earlier version and is therefore useless. What is the solution now if I need to create a table for a variable product with each variation showing on a separate line.

**Comment by mdibrahimk48** [comment]
Hello,

We sincerely apologize for any issues you are experiencing with our plugin. Our plugin has a lot of functionality that's why it looks complex. But please don't worry we will help you.

Please follow this helper documentation to show variation in a single column: https://wooproducttable.com/docs/doc/table-options/show-variation-name-in-a-single-column/?ref=56 

**Let us know if you encounter any issues.** 

Best regards,
Ibrahim

**Comment by bluewatersmarine** [comment]
Hi Ibrahim,

Thank you for your message. I have the pro version installed on my website but all the pro options are grayed out and not available and the single variation is not available under column type.

**Comment by bluewatersmarine** [comment]
I think my pro version license is not active on the website. I tried to find the place where to install my license code but I could not find it.

**Comment by mdibrahimk48** [comment]
Hi,

For this you need an addon plugin: https://codeastrology.com/downloads/simple-and-variation-products/?ref=56

For more details, you can contact us with a support ticket: https://codeastrology.com/my-support/

Best regards,
Ibrahim

**Comment by bluewatersmarine** [comment]
I went ahead and I bought the Addon but it did not change anything. My pro license is still not active and pro options are greyed out and the column type options are only limited to three options only.

**Comment by codersaiful** [comment]
You have to follow this documentation: https://wooproducttable.com/docs/doc/table-options/display-simple-and-variable-products-together

see https://demo.wooproducttable.com/simple-and-variation-products/

**Comment by bluewatersmarine** [comment]
This is very frustrating:

I HAVE THE PRO LICENSE. IF IT CAN CREATE WHAT I WANT AS IT IS MENTIONED IN THE ABOVE DOCUMENTATION, WHY WHY DID IBRAHIM MADE ME PAY FOR AND PURCHASE THE SIMPLE AND VARIATION PRODUCTS???? I NEED A REFUND FOR THIS.... AND ONE THING THAT NO BODY SEEMS TO CARE ABOUT..... MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....
MY PRO LICENSE IS NOT ACTIVE ON THE WEBSITE....

I HOPE I AM LOUD ENOUGH NOW FOR THIS PROBLEM TO BE FIXED.

**Comment by mdibrahimk48** [comment]
Hi there,

To show simple and variation products you need this addon. First, you have to save your license then you have to save it. 
If you face any issues please contact us with a ticket at: https://codeastrology.com/my-support/

We will provide you with full support. 

Thanks

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue as you are not responding. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.

Best regards,
Ibrahim
CodeAstrology
