### ISSUE TITLE
music player does not work if filters or search are used

### ISSUE THREAD

**Issue by hliuhka** [codersaiful/woo-product-table#316]
music player does not work if filters or search are used.

**Comment by mdibrahimk48** [comment]
We apologize for the inconvenience you're experiencing with our plugin.

Please share the URL of your table page. We need to check it from our end.

Best regards,
Ibrahim

**Comment by mdibrahimk48** [comment]
For getting more help please create a ticket at: https://codeastrology.com/my-support/ 

Best regards,
Ibrahim

**Comment by mdibrahimk48** [comment]
Hi there,

Please respond to our support ticket. We are waiting for your response!

Best regards,
Ibrahim

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can re-open this ticket or can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.

Best regards,
Ibrahim
Technical Support Engineer, CodeAstrology
