### ISSUE TITLE
Adding quantity for multiple variations of an item in "Quick_Qty" not working

### ISSUE THREAD

**Issue by shivmab1925** [codersaiful/woo-product-table#322]
Dear Code Astrology Team,

I hope this message finds you well.

Could you kindly review the attached video? It appears that the table is currently unable to accommodate multiple variations of a variable item to be added simultaneously. Whenever an additional variation is attempted, the previously added variation ceases to function.

https://github.com/codersaiful/woo-product-table/assets/88488679/efa336d9-2897-4f0c-a664-394d066c1357

To rectify this issue, it should allow for the addition of quantities for multiple variations of an item within "Quick_Qty."

For your convenience, here is the webpage for reference:
https://albastakitrading.com/
https://albastakitrading.com/wpt_product_table/all-items-order-page-parent-items/

Thank you for your attention to this matter.

Best regards,
Shiv Sharma

**Comment by mdibrahimk48** [comment]
Hi,

Thanks for reporting to us about this issue. Seems like your given URL is not working. Is the issue fixed from your end? 

Best regards,
Team CodeAstrology
