### ISSUE TITLE
How do I change the number of rows displayed in the goods table?

### ISSUE THREAD

**Issue by pixelpleks** [codersaiful/woo-product-table#323]
Hi !
![Screenshot_22](https://github.com/codersaiful/woo-product-table/assets/132206493/4950a1ed-2179-4ba4-b4e3-61fdc48bc077)

How do I change the number of rows displayed in the goods table?

**Comment by codersaiful** [comment]
From Configure tab change the Post Per Page quantity.

**Comment by pixelpleks** [comment]
it's not working

**Comment by mdibrahimk48** [comment]
Please create a ticket at: https://codeastrology.com/my-support/ 

We need more information to check this issue. 

Best regards,
Team CodeAstrology
