### ISSUE TITLE
Product with 2 variation, can't click add to cart

### ISSUE THREAD

**Issue by lalua158** [codersaiful/woo-product-table#325]
when product have 2 variation to choose. It not able to click add to cart. However, the product page is good but no active on product table page
<img width="1157" alt="image" src="https://github.com/codersaiful/woo-product-table/assets/166939994/1fe08ed3-f9af-4c09-abfc-e3c9b9d03641">

**Comment by mdibrahimk48** [comment]
Hello,

Could you share the URL? I have to check this from your site. 

Best regards,
Ibrahim

**Comment by lalua158** [comment]
https://b2b.noomfood.com/
ID: lantest
Pass: 123123
<img width="1222" alt="Screenshot 2024-04-14 at 10 01 48" src="https://github.com/codersaiful/woo-product-table/assets/166939994/07a8ff6f-840f-4d83-8c3f-e8e3ec475ad9">
Please test for product which have 2 row bulk variation 
Thank for your asap response

**Comment by mdibrahimk48** [comment]
Hello,

We need more information about your site regarding this issue. Please contact us through a support ticket at: https://codeastrology.com/my-support/

Best regards,
Ibrahim

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can re-open this ticket or create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible. Or can create a ticket at: https://codeastrology.com/my-support/ 

Thank you for choosing our plugin.

Best regards,
Team CodeAstrology
