### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Smartklink** [codersaiful/woo-product-table#331]
Sorting query not working. Keeps the same sorting tried every setting.

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can re-open this issue or can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.

Best regards,
CodeAstrology
