### ISSUE TITLE
Table broke after updates

### ISSUE THREAD

**Issue by ORU12** [codersaiful/woo-product-table#332]
As of a month ago our table was working correctly https://plasmidprosstg.wpengine.com/

<img width="1271" alt="How it should look" src="https://github.com/codersaiful/woo-product-table/assets/37853665/ab5a69c1-7257-47a6-aeb2-1d122e5b4f0c">

But after updating it is not lining up the columns correctly and not accepting the customer input for variations  https://plasmidpros.com/

![As it is now](https://github.com/codersaiful/woo-product-table/assets/37853665/c459aeb3-469b-494c-9d72-cb6a904aedf2)

I rolled Woo Product Table Pro - (Product Table by CodeAstrology) back to v 9.0.0 but it did not make a difference.
I have tested all plugins for conflicts and it did not help.

Any help would be appreciated.

**Comment by codersaiful** [comment]
Hello @ORU12 
Plz contact with [our support](https://codeastrology.com/my-support) 
And explain issue. If possible,  provide login details in ticket.
