### ISSUE TITLE
Woo-product-table

### ISSUE THREAD

**Issue by Sara1592** [codersaiful/woo-product-table#334]
mobile view is not speed and payment increment and decrement is not working

**Comment by codersaiful** [comment]
Hi, I appreciate your time and effort. Our development team will inspect the issue accordingly. Thanks

**Comment by codersaiful** [comment]
Could you please share more details regarding the issue? How do you reproduce the issue? Maybe with some screenshots or screencasts.

**Comment by Sara1592** [comment]
[screen-capture (3).webm](https://github.com/codersaiful/woo-product-table/assets/117970577/137fc647-7d29-47d6-a2bd-63bcf48fb5ea)

I have purchased a Woo Product Table. My website is https://rocketcrackers.com/ Sometimes this plugin works and Sometimes this plugin does not work.
please give me a solution. It's very urgent
