### ISSUE TITLE
Pressing the add to cart button may bloat my  server.

### ISSUE THREAD

**Issue by Orochikyocr** [codersaiful/woo-product-table#337]
I have been using this module for a couple of years. It is great, but in the last couple of weeks, I have been experiencing a slow to crashing website with my server RAM going from 20% to 200% of use in no time.
The reason is the AJAX add-to-cart buttons. Whenever I press that button the site does four requests, 3 of them going to admin-ajax.php
These requests could take up to 7 seconds combined to get resolved, sometimes less, sometimes way more time.
But the worst part is that any user can keep pressing the add to cart button spamming too many requests and overloading the admin-ajax.php, to the point that one simple user could lead my server from 20% of the RAM use to 70%. The server has 2GB. 
I made the test myself from Chrome, my server was at 20%, and then I pressed the add to cart button 30 times in less than 20 seconds. 
![image](https://github.com/user-attachments/assets/d482bec3-603c-42db-a944-6133b812895b)

![image](https://github.com/user-attachments/assets/797fc1e2-1ed1-44b9-b387-12337f7bf885)

I am looking for a way to disable the add to cart button for a couple of seconds after being pressed, maybe more time, cause this is easily abusable for any user who would want to slow down the website for anyone else.
![image](https://github.com/user-attachments/assets/c5860e97-b371-478a-82b3-ebee61df082a)

Please help. 
Thanks in advance.

**Comment by sarmina5** [comment]
Hello @Orochikyocr,

We are testing this issue from our end. We will share an update soon. 

Best regards,
Sarmin
CodeAstrology

**Comment by sarmina5** [comment]
Hello,

We have fixed this issue with our latest version. You may download this from GitHub or can wait for few days we will officially reelase this version in WordPress.

Best regards,
Sarmin
CodeAstrology

**Comment by mdibrahimk48** [comment]
I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
