### ISSUE TITLE
ACF Sub Fields

### ISSUE THREAD

**Issue by surinco** [codersaiful/woo-product-table#338]
using ACF subfield name does not work and empty values in columns are seen.

**Comment by sarmina5** [comment]
Hello @surinco,

Could you share more more details about this issue? If you could share a video to show us how you have trying to show the sub-fields value we can understand and test this from our local server. For more support you can contact us through: https://codeastrology.com/my-support/

Best regards,
Sarmin
CodeAstrology

**Comment by mdibrahimk48** [comment]
I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
