### ISSUE TITLE
Query Update in other languages 

### ISSUE THREAD

**Issue by EzioBelli91** [codersaiful/woo-product-table#339]
Hello,
I've noticed that when I select another language (spanish) from my primary language (italian) the results of the query are not updated. 
The results of query in the primary language and inside the Edit Product Table in the section "Query" are correct.

**Comment by sarmina5** [comment]
Hello,

Could you share the URL? 
If you could share a screen-recorded demonstration video? So, we can understand your situation and can help you? 

Best regards,
Sarmin
CodeAstrology

**Comment by mdibrahimk48** [comment]
I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
