### ISSUE TITLE
Incorrect <label> tag

### ISSUE THREAD

**Issue by tanyabouman** [codersaiful/woo-product-table#340]
There are a few places where the `<label>` tag is incorrectly spelled as `<lable>`.  It might break something in the WPML admin area, but I don't have that plugin, so I can't test it.
https://github.com/codersaiful/woo-product-table/blob/c0db75f0b2cab0f8dc31c6223d73b33809f10f86/inc/handle/checkbox-box.php#L43
https://github.com/codersaiful/woo-product-table/blob/c0db75f0b2cab0f8dc31c6223d73b33809f10f86/wpml/admin-area.php#L40
https://github.com/codersaiful/woo-product-table/blob/c0db75f0b2cab0f8dc31c6223d73b33809f10f86/wpml/admin-area.php#L103

**Comment by sarmina5** [comment]
Hello @tanyabouman,

Thanks for reporting. Our developer will test this and will share an update soon. 

Best regards,
Sarmin
CodeAstrology

**Comment by codersaiful** [comment]
@tanyabouman 
Hello, I have already fixed that spelling mistake. If you check [3.5.0.0](https://github.com/codersaiful/woo-product-table/tree/3.5.0.0) branch. you will get update.

Thanks
Saiful

**Comment by codersaiful** [comment]
https://github.com/codersaiful/woo-product-table/commit/9227d3f4ff98767f363db921b2cb9a613713f839

**Comment by codersaiful** [comment]
#c0db75f0b2cab0f8dc31c6223d73b33809f10f86

**Comment by sarmina5** [comment]
Hope this works fro you now. We closed this issue.
