### ISSUE TITLE
Can't add product to quote with Yith

### ISSUE THREAD

**Issue by Natoun50** [codersaiful/woo-product-table#345]
Hi, I’m having an issue on my website. Some of my customers can’t add a product to their quote. When they click on “Add to quote”, the button changes to “Adding…” but nothing else happens.

I hope you’ll be able to help me.

Thank you

**Comment by sarmina5** [comment]
Could you please share the URL? So we can test this from our end. 

Regards,
CodeAstrology Team

**Comment by mdibrahimk48** [comment]
Hi,

As you are not responding we assumed that your issue is fixed.

Best regards,
