### ISSUE TITLE
when added any variation settings, cannot add variable product to cart from woo table

### ISSUE THREAD

**Issue by ankita612** [codersaiful/woo-product-table#347]
I have set attribute like this: 
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/39b186f6-3958-4614-96c4-105dfdf4039f">

and then variation is like this
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/7271866d-3728-40d0-82d4-b4065172102e">
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/39fae619-7a50-4f9f-bb57-16c1a7c8e9d1">

Now when i select the same product on the table and select the varuation, it still complains that no variation has been selected
<img width="1488" alt="image" src="https://github.com/user-attachments/assets/51555f61-5aec-49c7-8942-ccfd020725a6">

if i do use normal woo commerce product table i see no issues
<img width="1488" alt="image" src="https://github.com/user-attachments/assets/e04cc890-6bd4-416e-99c9-ca39aaa3bc4d">

**Comment by sarmina5** [comment]
**_Hello Ankita,_**

We have checked your this site: https://new.swaad.com.au/order-online/
We have found that your site's shows some JavaScripts error: ⤵ 
![image](https://github.com/user-attachments/assets/70ee5887-197c-4687-bd26-b36f8a6b9198)


We need more information related to your site to check this issue. 
Please create a ticket at: https://codeastrology.com/my-support/ 

**_Best regards,
Team CodeAstrology_**

**Comment by ankita612** [comment]
Thanks I have created the ticket. Please see if you could help as then I can use your plugin else would have to choose another option
https://codeastrology.com/my-support/#/ticket/614

**Comment by sarmina5** [comment]
Thanks for creating ticket. We will check and reach you ASAP.

Best regards,
Team CodeAstrology
