### ISSUE TITLE
Ajax page does not work in the woocommerce archives from page 2

### ISSUE THREAD

**Issue by DEV-JWebers** [codersaiful/woo-product-table#74]
Hi, I have the Astra Free Theme with all the add-ons updated to the latest versions available and its add-on does not work properly. 
I tried these 3 ways:

1. Paging enabled + Ajax:
It shows 2 pages the theme page and the add-on page. If I click on the theme page, it will change but no new products will be shown.
If I click on the add-on page, only the table view changes, but the pagination disappears and you can neither move forward nor return to the page.

2.Pagination without ajax:
In this case, the 2 pages will be displayed: theme and plugin. When I click on the plugin page, the theme and plugin pages advance. But the products do not change.

3. I disable ajax and paging:
Only the theme page is shown and you can advance the theme page but the products do not change.

You can tell me what the problem is.

**Comment by codersaiful** [comment]
I think, you are using our pro version.
Fyi: in archive page, all features of plugin will not work for archive information.
you can contact over our support.
Thanks

**Comment by benhadad** [comment]
What features work in product archive (category pages).  And is there a demo/tutorial how to use it on the category pages?

**Comment by fazlebarisn** [comment]
Hello,
You can display a table on every archive page. ( https://wooproducttable.com/product-table-woocommerce-archive-category-tag-attribute-page/ ) like shop, Category, Tag, etc
Table on shop page - https://demo.wooproducttable.com/shop/
Table on 'Fashion' category page - https://demo.wooproducttable.com/product-category/fashion/

Our search, pagination, or load more button is not gonna work on the archive page. You can use the default function (search, pagination, or load) and it will work with table. 
Display Table On Specific Archive page - https://wooproducttable.com/display-table-on-specific-archive-page-category-tag-attribute-page/
All docs - https://wooproducttable.com/documentation/

Regards

**Comment by codersaiful** [comment]
All docs - https://wooproducttable.com/documentation/

For making a new  page like archive, you have to make a new page  with all feature of our product table.

And I things, this topic should close.
