### ISSUE TITLE
How to add a column

### ISSUE THREAD

**Issue by db-conception** [codersaiful/woo-product-table#75]
Hello,

I am trying to add a column but nothing appends when I just add this code 

```php
if( !function_exists( 'new_shortcode_column' ) ){
   function new_shortcode_column( $column_array ) {
       $column_array['new_shortcode'] = 'New Shortcode';
       return $column_array;
   }
}
add_filter( 'wpto_default_column_arr', 'new_shortcode_column' );
```

I should see after adding this code a new column with title 'New Shortcode' but blank for each line content no ?

Regards

**Comment by codersaiful** [comment]
Hello Sir, this issue has solved. Please check latest version. 
To this latest version, you able to add new column by using filter from any where.
but on old version, there was need to code from plugin actually.

thanks a lot

**Comment by db-conception** [comment]
Hello Sir,

Can you tell me step by step how to add colomn with custom content from functions.php ? 

Best regards,

**Comment by codersaiful** [comment]
Ok, today I will show u.  Thanks

**Comment by db-conception** [comment]
Hello Sir,

You forget me :). 
I look at wordpress plugin's page but neither update is provided for your plugin. My version is  2.8.2.

Best regards

**Comment by moreaupascal56** [comment]
Hello and sorry to reactive this issue but it seems I have the same issue @db-conception, did you manage to make it work? Regards and Thankyou!

**Comment by moreaupascal56** [comment]
> Hello Sir,
> 
> You forget me :).
> I look at wordpress plugin's page but neither update is provided for your plugin. My version is 2.8.2.
> 
> Best regards

Hello and sorry to reactive this issue but it seems I have the same issue @db-conception, did you manage to make it work? Regards and Thankyou!
