### ISSUE TITLE
Variation labels appear even when wpt_show_variation_label is not set.

### ISSUE THREAD

**Issue by tanyabouman** [codersaiful/woo-product-table#83]
Specifically, my problem is that the labels are showing up, but because `$show_label` is false, they are not inside the `<div class="variation-wrapper">` and that makes the format look bad.

For me, it solves the problem to wrap an if-statement around the label code in `variation_html.php`.
```
                <?php if ( $show_label ) { ?>
                        <label for="<?php echo esc_attr( esc_attr( $attribute_name . '_' . $product->get_id() ) );?>"><?php echo esc_html( wc_attribute_label( $attribute_name ) ); ?></label>
                <?php } ?>
```
Does that make sense as a solution?  If this is a good solution, I can make a pull request.

**Comment by codersaiful** [comment]
I think, you r right. We have to add this snippet to our plugin.

**Comment by codersaiful** [comment]
Did u mean, Issue still ......?

**Comment by tanyabouman** [comment]
It's fixed.  Thank you
