### ISSUE TITLE
Icon only renders add to cart button to small

### ISSUE THREAD

**Issue by davidwuest** [codersaiful/woo-product-table#91]
If "Icon only" is set, the button renders smaller than the icon.

**Comment by codersaiful** [comment]
thanks for your suggestion. I will fix it out.

**Comment by davidwuest** [comment]
Thanks. Let me know when it is done, so I can pull the update.

**Comment by dannyfu79** [comment]
Hi, I have a question about the Add to Cart button too. I've created a variable product (with variations) table fine, but when adding anything to the cart, **the cart button disappears** and therefore can't add any more of that product. So no good, if a customer wants to buy multiple variations of a particular product. Instead a view basket button replaces where the add to cart once was. Is this something I can change in the free licence version of the plugin and would appreciate any help with resolving this.

![image](https://user-images.githubusercontent.com/88591303/128607388-4f87be34-f104-429b-9e86-8e472c766a1e.png)
![image](https://user-images.githubusercontent.com/88591303/128607409-b0073e8d-165d-4103-9cc4-4124726f65ee.png)

**Comment by dannyfu79** [comment]
> thanks for your suggestion. I will fix it out.

Please can you help me resolve the missing Add to Cart button issue, once it's been used once? details below

**Comment by davidwuest** [comment]
What's the status on this?

**Comment by codersaiful** [comment]
Can u provide a screenshot please.

**Comment by codersaiful** [comment]
Problem already solved
