### ISSUE TITLE
Wordpress 5.7.2 Update makes some features unstable

### ISSUE THREAD

**Issue by rayfosterCFA** [codersaiful/woo-product-table#97]
Hi,
It appears the new wordpress updates breaks some functionality in the plugin from the backend.
We have updated to your latest version of your plugin. However it seems that some functionality breaks:
- Expanding columns in backend (Table Configuration)
- Adding new columns to table doesn't appear to do anything

Thanks!

**Comment by codersaiful** [comment]
Hello, Based on our Latest Woo Product Table Plugin, you need minimum **7.0.6** of **Pro**([Woo Product Table Pro](https://codecanyon.net/item/woo-product-table-pro/20676867)). and  we have also fixed some issue on our latest free version. Please check and let us know.

By the way, Thanks a lot for your comment.
